# https://taskfile.dev

version: '2'

tasks:

  docker:run:
    cmds:
      #- sudo chown -R 33:33 $PWD/containerdata
      - docker run --rm --cap-add=NET_ADMIN --net=host -it -v $PWD/containerdata:/container container_pxeserver

  docker:build:
    cmds:
      - docker build . -t container_pxeserver

  docker:debug:
    cmds:
      - docker run --rm --cap-add=NET_ADMIN --net=host -it -v $PWD/containerdata:/container container_pxeserver bash -c "/start.sh && service nginx start && service php7.0-fpm start; echo 'run dnsmasq --no-daemon --log-queries --log-facility=/container/dnsmasq.log'; bash"

  git:pull:
    cmds:
      - git reset --hard origin/master
      - git pull
