# https://taskfile.dev

version: '2'

tasks:

  # build the 'containered_go' docker-image
  build:
    cmds:
      - docker build . -t containered_go
      
  # run the 'containered_go' docker-image in detached mode
  run:
    cmds:
      - docker run --name go --rm -v $PWD:/build containered_go