# https://taskfile.dev

version: '2'

tasks:

  # create / load initial files/containers
  init:
    cmds:
      - task: init:sshkey
      - cd pxe; task init


  # create ssh-key-pair if no public key exists
  init:sshkey:
    cmds:
      - read -s "Please enter your email for the ssh-key:" email
      - ssh-keygen -b 4096 -t rsa -f ./key -C "$email" -N "" <<< y
    status:
      - test -f ./key.pub
  # load ssh-public-key from github
  #sshkeyload:
  #  cmds:
  #    - cd ./pxe/containerdata/public; wget https://github.com/tillhoff.keys -O key.pub


  # run the software
  run:
    cmds:
      - cd pxe; task run
