# https://taskfile.dev

version: '2'

tasks:

  # create / load initial files/containers
  init:
    cmds:
      - task: init:sshkey
      - cd golang; task build
      - cd golang; task run
      - cp golang/main pxe/containerdata/go/main
      - cp golang/*.tmpl pxe/containerdata/go/
      - cd pxe; task init


  # create ssh-key-pair if no public key exists
  init:sshkey:
    cmds:
      - ./ssh-keygen.sh
    status:
      - test -f ./key.pub
  # load ssh-public-key from github
  #sshkeyload:
  #  cmds:
  #    - cd ./pxe/containerdata/public; wget https://github.com/tillhoff.keys -O key.pub


  # run the software
  run:
    cmds:
      - cd pxe; task run
    preconditions:
      - test -f ./key.pub
      - test -f ./pxe/containerdata/web/netboot/pxelinux.0


  # reboot a host
  reboot:
    cmds:
      - ./scripts/reboot.sh

  
  # ssh into a host
  ssh:
    cmds:
      - ./scripts/ssh.sh
