# https://taskfile.dev

version: '2'

tasks:

  # create / load initial files/containers
  init:
    cmds:
      - task: init:sshkeygen
      - cd pxe; task init
      - cd ansible; task init


  # create ssh-key-pair if no public key exists
  init:sshkey:
    cmds:
      - cd ./; ssh-keygen -b 4096 -t rsa -f ./key -N "" <<< y
    status:
      - test -f ./key.pub
  # load ssh-public-key from github
  #sshkeyload:
  #  cmds:
  #    - cd ./pxe/containerdata/public; wget https://github.com/tillhoff.keys -O key.pub


  # run the software
  run:
    cmds:
      - cd pxe; task run
      - cd ansible; task run







  # force rebuild of the 'pxe-server with ansible' docker-image
  force:rebuild:pxeansible:
    cmds:
      - cd ./pxe; docker build . -t container_pxeansible --no-cache
