# https://taskfile.dev

version: '2'

tasks:

  # initialize this image
  init:
    cmds:
      - task: build

  # build the 'containered_ansible' docker-image
  build:
    cmds:
      - docker build . -t containered_ansible

  # run the 'containered_ansible' docker-image
  run:
    cmds:
      - docker run --rm --cap-add=NET_ADMIN --net=host -it -v $PWD/../ansible_hosts:/etc/ansible/hosts -v $PWD/containerdata:/container -v $PWD/../key.pub:/key/key.pub containered_ansible

  # stop all 'containered_ansible' docker-containers
  stop:
    cmds:
      - docker stop containered_ansible
      - docker rm containered_ansible
