# https://taskfile.dev

version: '2'

tasks:

  # build the 'containered_go_compiler' docker-image
  build:
    cmds:
      - docker build . -t containered_go_compiler
      
  # run the 'containered_go_compiler' docker-image in detached mode
  run:
    cmds:
      - docker run --name go-compiler --rm -v $PWD:/build containered_go_compiler

  # stop all 'containered_go_compiler' docker-containers
  stop:
    cmds:
      - docker stop go-compiler