# https://taskfile.dev

version: '2'

tasks:

  # run the go-builder and compile into binary
  compile:
    cmds:
      - docker run --name go-builder --rm -v $PWD:/go/src/app tillhoff/go-builder

  # stop all 'go-builder' docker-containers
  stop:
    cmds:
      - docker stop go-builder